In [17]:
import pandas as pd
import numpy as np
import plotly.express as px

pd.set_option('display.max_rows', 100)

In [18]:
kb = pd.read_excel('KB국민_지역별세부음식.xlsx')
bc = pd.read_excel('BC카드_온라인.xlsx')
seoul = pd.read_excel('신한_서울시지역.xlsx')
city = pd.read_excel('신한카드_광역시별.xlsx')

## KB 데이터 - 요식업 관련

In [12]:
kb.describe()

,기준년도,기준월,신용카드보유,체크카드보유,회원수,매출건수,가맹점수,순위
count,100.0,100.0,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,2019.0,3.0,0.730000,0.540000,59.300000,77.14000,12.360000,15.740000
std,0.0,0.0,0.446196,0.500908,104.438615,150.80518,23.694401,12.326878
min,2019.0,3.0,0.000000,0.000000,5.000000,5.00000,1.000000,1.000000
25%,2019.0,3.0,0.000000,0.000000,11.000000,12.75000,3.000000,4.750000
50%,2019.0,3.0,1.000000,1.000000,26.500000,32.50000,5.000000,14.000000
75%,2019.0,3.0,1.000000,1.000000,60.000000,76.00000,11.000000,23.750000
max,2019.0,3.0,1.000000,1.000000,745.000000,1176.00000,161.000000,46.000000

In [13]:
kb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   기준년도        100 non-null    int64
 1   기준월         100 non-null    int64
 2   한글시도명       100 non-null    object
 3   한글시군구명      100 non-null    object
 4   법정동리명       100 non-null    object
 5   마케팅업종중분류명   100 non-null    object
 6   마케팅업종세분류명   100 non-null    object
 7   마케팅업종세세분류명  100 non-null    object
 8   성별구분        100 non-null    object
 9   연령대         100 non-null    object
 10  신용카드보유      100 non-null    int64
 11  체크카드보유      100 non-null    int64
 12  회원수         100 non-null    int64
 13  매출건수        100 non-null    int64
 14  가맹점수        100 non-null    int64
 15  순위          100 non-null    int64
dtypes: int64(8), object(8)
memory usage: 12.6+ KB

In [14]:
kb.head(3)

,기준년도,기준월,한글시도명,한글시군구명,법정동리명,마케팅업종중분류명,마케팅업종세분류명,마케팅업종세세분류명,성별구분,연령대,신용카드보유,체크카드보유,회원수,매출건수,가맹점수,순위
0,2019,3,경기도,성남시 분당구,정자동,한식,국/탕/백반류,김치찜/찌개전문점,01.남성,3.40대,1,1,26,31,2,46
1,2019,3,경기도,성남시 분당구,수내동,일식,밥요리,덮밥/가정식전문점,02.여성,3.40대,1,0,29,36,2,45
2,2019,3,서울특별시,강남구,논현동,한식,국/탕/백반류,부대찌개전문점,02.여성,3.40대,1,1,78,85,13,42

In [15]:
''' - KB국민
    기준년도
    기준월
    한글시도명 : 서울특별시
    한글시군구명 : 강남구
    법정동리명 : 논현동
    마케팅업종증분류명 : 한식
    마케팅업종세분류명 : 김치찜/찌개
    성별구분 : 01.남성
    연령대 : 3.40대
    신용카드보유 : 1
    체크카드보유 : 1
    회원수 : 26
    매출건수 : 31
    가맹점수 : 2
    순위 : 45
'''

' - KB국민\n    기준년도\n    기준월\n    한글시도명 : 서울특별시\n    한글시군구명 : 강남구\n    법정동리명 : 논현동\n    마케팅업종증분류명 : 한식\n    마케팅업종세분류명 : 김치찜/찌개\n    성별구분 : 01.남성\n    연령대 : 3.40대\n    신용카드보유 : 1\n    체크카드보유 : 1\n    회원수 : 26\n    매출건수 : 31\n    가맹점수 : 2\n    순위 : 45\n'

In [16]:
kb.sort_values(by='순위')

,기준년도,기준월,한글시도명,한글시군구명,법정동리명,마케팅업종중분류명,마케팅업종세분류명,마케팅업종세세분류명,성별구분,연령대,신용카드보유,체크카드보유,회원수,매출건수,가맹점수,순위
99,2019,3,서울특별시,마포구,신공덕동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,1,0,6,8,4,1
85,2019,3,서울특별시,강남구,수서동,한식,국/탕/백반류,일반한식/백반,01.남성,5.50대,1,0,410,527,29,1
86,2019,3,서울특별시,마포구,대흥동,한식,국/탕/백반류,일반한식/백반,02.여성,3.40대,1,0,67,80,23,1
87,2019,3,서울특별시,마포구,성산동,한식,국/탕/백반류,일반한식/백반,01.남성,5.50대,1,1,184,288,41,1
88,2019,3,서울특별시,강남구,수서동,한식,국/탕/백반류,일반한식/백반,02.여성,5.50대,1,1,304,345,26,1
89,2019,3,서울특별시,마포구,대흥동,한식,국/탕/백반류,일반한식/백반,02.여성,2.30대,1,1,86,106,20,1
90,2019,3,서울특별시,마포구,염리동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,1,0,76,88,12,1
98,2019,3,서울특별시,강남구,대치동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,1,1,231,310,97,1
92,2019,3,경기도,성남시 분당구,삼평동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,0,1,12,12,7,1
97,2019,3,경기도,성남시 분당구,수내동,한식,국/탕/백반류,일반한식/백반,01.남성,6.60대,1,1,123,190,38,1
96,2019,3,서울특별시,마포구,마포동,한식,국/탕/백반류,일반한식/백반,01.남성,3.40대,1,1,30,50,9,1
91,2019,3,서울특별시,강남구,세곡동,한식,국/탕/백반류,일반한식/백반,01.남성,1.20대이하,0,1,31,41,11,1
94,2019,3,서울특별시,마포구,신공덕동,한식,국/탕/백반류,일반한식/백반,01.남성,1.20대이하,0,1,11,11,3,1
93,2019,3,경기도,성남시 분당구,야탑동,한식,국/탕/백반류,일반한식/백반,02.여성,2.30대,1,0,129,171,44,1
95,2019,3,경기도,성남시 분당구,정자동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,1,0,370,487,75,1
84,2019,3,서울특별시,강남구,신사동,한식,국/탕/백반류,일반한식/백반,01.남성,3.40대,1,1,745,1176,161,2
83,2019,3,서울특별시,강남구,청담동,한식,국/탕/백반류,일반한식/백반,02.여성,6.60대,0,1,33,46,25,2
81,2019,3,서울특별시,마포구,서교동,일식,해산물,일식전문점,01.남성,6.60대,1,0,36,44,25,2
82,2019,3,서울특별시,마포구,신공덕동,한식,국/탕/백반류,일반한식/백반,02.여성,2.30대,0,1,6,6,2,2
80,2019,3,서울특별시,강남구,도곡동,한식,돼지고기,삼겹살/구이전문점,01.남성,2.30대,1,1,134,178,12,3
79,2019,3,서울특별시,강남구,개포동,한식,면요리,국수/칼국수전문점,02.여성,6.60대,1,0,30,39,5,3
78,2019,3,서울특별시,강남구,삼성동,한식,면요리,국수/칼국수전문점,01.남성,6.60대,1,1,25,33,9,3
75,2019,3,경기도,성남시 분당구,이매동,한식,국/탕/백반류,일반한식/백반,01.남성,6.60대,1,1,69,114,11,4
77,2019,3,서울특별시,마포구,서교동,한식,국/탕/백반류,일반한식/백반,01.남성,2.30대,1,0,347,452,127,4
76,2019,3,경기도,성남시 분당구,분당동,한식,국/탕/백반류,일반한식/백반,02.여성,2.30대,1,1,12,18,3,4
74,2019,3,서울특별시,마포구,용강동,한식,돼지고기,돼지갈비전문점,01.남성,2.30대,1,1,39,40,4,5
72,2019,3,경기도,성남시 분당구,야탑동,한식,돼지고기,삼겹살/구이전문점,02.여성,2.30대,1,1,69,76,11,6
73,2019,3,서울특별시,마포구,용강동,한식,돼지고기,삼겹살/구이전문점,02.여성,1.20대이하,0,1,14,15,5,6
69,2019,3,경기도,성남시 분당구,수내동,한식,돼지고기,삼겹살/구이전문점,02.여성,2.30대,1,1,37,41,6,7
70,2019,3,서울특별시,마포구,공덕동,한식,국/탕/백반류,순대전문점,01.남성,2.30대,1,1,30,32,2,7
71,2019,3,경기도,성남시 분당구,수내동,한식,돼지고기,삼겹살/구이전문점,01.남성,3.40대,1,1,71,82,8,7
68,2019,3,경기도,성남시 분당구,삼평동,양식,종합양식,종합양식,01.남성,5.50대,1,0,60,76,16,8
67,2019,3,서울특별시,강남구,도곡동,한식,돼지고기,족발전문점,02.여성,2.30대,1,0,14,16,3,8
66,2019,3,서울특별시,마포구,성산동,일식,해산물,일식전문점,02.여성,3.40대,1,0,25,28,5,9
65,2019,3,경기도,성남시 분당구,판교동,양식,종합양식,종합양식,02.여성,2.30대,1,0,5,11,5,9
64,2019,3,서울특별시,강남구,삼성동,양식,종합양식,종합양식,01.남성,1.20대이하,1,1,272,369,29,9
63,2019,3,경기도,성남시 분당구,구미동,일식,해산물,초밥전문점,02.여성,2.30대,1,0,14,17,4,9
62,2019,3,경기도,성남시 분당구,구미동,한식,돼지고기,삼겹살/구이전문점,01.남성,2.30대,1,1,65,69,10,9
61,2019,3,서울특별시,마포구,공덕동,일식,해산물,초밥전문점,02.여성,5.50대,0,0,6,6,3,10
58,2019,3,서울특별시,강남구,일원동,한식,국/탕/백반류,순대전문점,01.남성,3.40대,1,0,68,78,3,11
60,2019,3,서울특별시,강남구,대치동,한식,돼지고기,보쌈전문점,02.여성,3.40대,1,0,81,106,4,11
59,2019,3,경기도,성남시 분당구,정자동,한식,면요리,냉면전문점,01.남성,3.40대,1,0,23,27,3,11
57,2019,3,서울특별시,강남구,수서동,한식,돼지고기,삼겹살/구이전문점,01.남성,5.50대,0,1,6,7,3,12
56,2019,3,경기도,성남시 분당구,서현동,양식,종합양식,종합양식,01.남성,1.20대이하,1,0,11,11,8,13
55,2019,3,서울특별시,강남구,도곡동,한식,소고기,곱창/양구이전문점,02.여성,1.20대이하,1,0,7,12,3,13
54,2019,3,경기도,성남시 분당구,금곡동,양식,종합양식,종합양식,02.여성,2.30대,1,0,15,17,4,13
53,2019,3,서울특별시,마포구,망원동,양식,종합양식,종합양식,02.여성,3.40대,0,1,24,35,11,13
52,2019,3,경기도,성남시 분당구,삼평동,한식,국/탕/백반류,순대전문점,01.남성,5.50대,1,1,50,77,6,13
51,2019,3,서울특별시,강남구,대치동,일식,해산물,초밥전문점,02.여성,2.30대,1,0,41,48,10,13
50,2019,3,경기도,성남시 분당구,서현동,한식,돼지고기,족발전문점,01.남성,5.50대,1,0,28,31,6,14
49,2019,3,경기도,성남시 분당구,운중동,한식,국/탕/백반류,순대전문점,01.남성,3.40대,1,1,30,46,2,14
47,2019,3,경기도,성남시 분당구,금곡동,한식,국/탕/백반류,설렁탕/곰탕전문점,01.남성,3.40대,0,1,7,11,1,14
48,2019,3,서울특별시,강남구,삼성동,한식,면요리,국수/칼국수전문점,01.남성,6.60대,0,0,5,5,4,14
46,2019,3,경기도,성남시 분당구,구미동,한식,해산물,낙지/쭈꾸미전문점,01.남성,2.30대,1,1,34,36,5,14
45,2019,3,서울특별시,강남구,일원동,한식,국/탕/백반류,해장국/감자탕,02.여성,1.20대이하,0,1,13,13,1,15
44,2019,3,서울특별시,마포구,공덕동,일식,밥요리,덮밥/가정식전문점,01.남성,2.30대,1,0,8,9,1,15
43,2019,3,서울특별시,강남구,신사동,한식,해산물,횟집,02.여성,1.20대이하,1,0,15,17,2,15
42,2019,3,서울특별시,마포구,망원동,한식,소고기,곱창/양구이전문점,02.여성,3.40대,0,0,10,10,5,15
41,2019,3,경기도,성남시 분당구,수내동,한식,해산물,낙지/쭈꾸미전문점,01.남성,5.50대,1,1,18,21,1,16
40,2019,3,서울특별시,마포구,서교동,한식,국/탕/백반류,부대찌개전문점,02.여성,1.20대이하,0,1,111,119,5,16
39,2019,3,경기도,성남시 분당구,수내동,한식,돼지고기,족발전문점,02.여성,6.60대,1,0,12,13,5,16
38,2019,3,경기도,성남시 분당구,수내동,한식,돼지고기,족발전문점,02.여성,2.30대,1,1,14,15,5,16
37,2019,3,경기도,성남시 분당구,야탑동,한식,국/탕/백반류,설렁탕/곰탕전문점,02.여성,6.60대,1,0,128,154,3,16
36,2019,3,경기도,성남시 분당구,야탑동,한식,면요리,국수/칼국수전문점,01.남성,6.60대,1,1,60,76,13,18
34,2019,3,서울특별시,강남구,신사동,한식,해산물,오징어전문점,02.여성,2.30대,1,0,10,11,2,19
35,2019,3,서울특별시,마포구,성산동,일식,해산물,초밥전문점,02.여성,2.30대,0,1,7,7,2,19
33,2019,3,서울특별시,마포구,동교동,양식,종합양식,종합양식,02.여성,6.60대,1,1,7,7,4,20
32,2019,3,경기도,성남시 분당구,삼평동,한식,면요리,국수/칼국수전문점,02.여성,5.50대,0,0,12,17,9,20
31,2019,3,서울특별시,마포구,상암동,일식,해산물,일식전문점,01.남성,2.30대,1,0,40,52,21,20
30,2019,3,서울특별시,마포구,공덕동,한식,해산물,낙지/쭈꾸미전문점,01.남성,1.20대이하,1,1,11,11,1,22
29,2019,3,서울특별시,마포구,동교동,한식,면요리,우동전문점,02.여성,5.50대,1,0,37,40,4,22
28,2019,3,서울특별시,강남구,삼성동,한식,국/탕/백반류,샤브샤브전문점,02.여성,3.40대,1,1,9,10,2,22
27,2019,3,서울특별시,강남구,신사동,한식,돼지고기,족발전문점,02.여성,1.20대이하,1,1,46,47,7,23
26,2019,3,서울특별시,강남구,논현동,한식,국/탕/백반류,부대찌개전문점,02.여성,5.50대,1,0,50,56,13,23
25,2019,3,서울특별시,강남구,신사동,한식,면요리,국수/칼국수전문점,01.남성,5.50대,1,1,36,42,12,23
23,2019,3,경기도,성남시 분당구,야탑동,한식,면요리,국수/칼국수전문점,02.여성,2.30대,0,0,15,15,6,26
24,2019,3,경기도,성남시 분당구,야탑동,한식,해산물,오징어전문점,01.남성,1.20대이하,0,1,32,33,3,26
22,2019,3,서울특별시,강남구,삼성동,일식,돼지고기,돈가스전문점,02.여성,2.30대,1,0,42,50,7,27
21,2019,3,경기도,성남시 분당구,야탑동,한식,돼지고기,족발전문점,01.남성,2.30대,1,0,23,24,5,28
20,2019,3,서울특별시,마포구,도화동,한식,닭고기,삼계탕/백숙전문점,02.여성,3.40대,1,0,13,14,3,28
19,2019,3,서울특별시,마포구,상암동,한식,해산물,낙지/쭈꾸미전문점,01.남성,3.40대,1,1,32,33,3,29
18,2019,3,서울특별시,마포구,아현동,한식,돼지고기,족발전문점,01.남성,3.40대,1,1,11,16,2,29
17,2019,3,서울특별시,강남구,대치동,한식,국/탕/백반류,해장국/감자탕,02.여성,3.40대,1,1,134,154,8,29
16,2019,3,경기도,성남시 분당구,서현동,한식,닭고기,닭갈비전문점,02.여성,2.30대,0,1,8,9,2,29
15,2019,3,서울특별시,마포구,염리동,한식,국/탕/백반류,죽전문점,02.여성,5.50대,1,1,6,7,1,30
14,2019,3,경기도,성남시 분당구,수내동,한식,돼지고기,삼겹살/구이전문점,02.여성,3.40대,0,1,17,19,7,31
13,2019,3,경기도,성남시 분당구,금곡동,한식,해산물,생선구이/찜전문점,02.여성,6.60대,1,0,27,38,2,31
11,2019,3,서울특별시,마포구,상수동,한식,기타고기,기타고기요리전문점,02.여성,5.50대,1,0,8,10,3,32
12,2019,3,서울특별시,강남구,논현동,한식,국/탕/백반류,국밥전문점,02.여성,6.60대,0,0,10,11,3,32
10,2019,3,경기도,성남시 분당구,판교동,한식,면요리,냉면전문점,01.남성,1.20대이하,0,1,9,10,2,33
9,2019,3,서울특별시,마포구,상암동,한식,돼지고기,족발전문점,02.여성,5.50대,1,1,9,10,6,34
8,2019,3,경기도,성남시 분당구,정자동,한식,국/탕/백반류,죽전문점,02.여성,1.20대이하,0,1,21,26,4,36
7,2019,3,서울특별시,강남구,대치동,한식,해산물,생선구이/찜전문점,01.남성,5.50대,0,0,5,6,2,36
6,2019,3,서울특별시,강남구,신사동,한식,국/탕/백반류,콩나물국밥전문점,01.남성,5.50대,1,0,15,19,3,38
5,2019,3,서울특별시,마포구,염리동,한식,면요리,냉면전문점,02.여성,3.40대,0,0,11,19,3,40
4,2019,3,서울특별시,마포구,공덕동,한식,면요리,냉면전문점,01.남성,3.40대,0,1,8,13,2,40
3,2019,3,서울특별시,마포구,서교동,양식,종합양식,종합양식,02.여성,3.40대,0,0,29,34,21,40
2,2019,3,서울특별시,강남구,논현동,한식,국/탕/백반류,부대찌개전문점,02.여성,3.40대,1,1,78,85,13,42
1,2019,3,경기도,성남시 분당구,수내동,일식,밥요리,덮밥/가정식전문점,02.여성,3.40대,1,0,29,36,2,45
0,2019,3,경기도,성남시 분당구,정자동,한식,국/탕/백반류,김치찜/찌개전문점,01.남성,3.40대,1,1,26,31,2,46

## BC 카드 - 온라인 매출액

In [ ]:
''' - BC카드
    기준연월
    대분류_품목코드 : 11
    대분류_품목명 : 패션잡화
    중분류_품목코드 : 1112
    중분류_품목명 : 가방
    성별 : 여성
    연령대 : 40대
    라이프사이클 : 초중고자녀가구
    광역시도_코드 : 28
    광역시도_명칭 : 인천광역시
    시군구코드 : 2826
    시군구명칭 : 서구
    법정동코드 : 2826011300
    법정동명칭 : 마전동
    고객수 : 7
    매출금액 : 1304670
    매출건수 : 9
'''

In [19]:
bc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   기준연월      100 non-null    int64
 1   대분류_품목코드  100 non-null    int64
 2   대분류_품목명   100 non-null    object
 3   중분류_품목코드  100 non-null    int64
 4   중분류_품목명   100 non-null    object
 5   성별        100 non-null    object
 6   연령대       100 non-null    object
 7   라이프사이클    100 non-null    object
 8   광역시도_코드   100 non-null    int64
 9   광역시도_명칭   100 non-null    object
 10  시군구코드     100 non-null    int64
 11  시군구명칭     100 non-null    object
 12  법정동코드     100 non-null    int64
 13  법정동명칭     100 non-null    object
 14  고객수       100 non-null    int64
 15  매출금액      100 non-null    int64
 16  매출건수      100 non-null    int64
dtypes: int64(9), object(8)
memory usage: 13.4+ KB

In [20]:
bc.head(3)

,기준연월,대분류_품목코드,대분류_품목명,중분류_품목코드,중분류_품목명,성별,연령대,라이프사이클,광역시도_코드,광역시도_명칭,시군구코드,시군구명칭,법정동코드,법정동명칭,고객수,매출금액,매출건수
0,201903,11,패션잡화,1112,가방,여성,40대,초중고자녀가구,28,인천광역시,2826,서구,2826011300,마전동,7,1304670,9
1,201903,11,패션잡화,1112,가방,여성,40대,초중고자녀가구,11,서울특별시,1168,강남구,1168011800,도곡동,5,2406403,8
2,201903,11,패션잡화,1112,가방,여성,40대,신혼영유아가구,11,서울특별시,1130,강북구,1130510300,수유동,5,305227,4

## 신한카드 - 광역시별 데이터 : 업종 매출

In [21]:
city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준년월    100 non-null    int64
 1   광역시도명   100 non-null    object
 2   업종대분류   100 non-null    object
 3   업종중분류   100 non-null    object
 4   업종소분류   100 non-null    object
 5   신규가맹점수  100 non-null    int64
 6   해지가맹점수  100 non-null    int64
 7   매출가맹점수  100 non-null    int64
 8   카드매출금액  100 non-null    int64
 9   카드매출건수  100 non-null    int64
 10  점당매출금액  100 non-null    int64
 11  건당매출금액  100 non-null    int64
dtypes: int64(8), object(4)
memory usage: 9.5+ KB

In [23]:
''' - 신한카드 : 광역시별
    기준년월
    광역시도명 : 강원
    업종대분류 : 문화레져
    업종중분류 : 동물
    업종소분류 : 동물농장
    신규가맹점수 : 5
    해지가맹점수 : 1
    매출가맹점수 : 8
    카드매출금액 : 11947000
    카드매출건수 : 417
    점당매출금액 : 1493377
    건당매출금액 : 28650
'''

' - 신한카드 : 광역시별\n    기준년월\n    광역시도명 : 강원\n    업종대분류 : 문화레져\n    업종중분류 : 동물\n    업종소분류 : 동물농장\n    신규가맹점수 : 5\n    해지가맹점수 : 1\n    매출가맹점수 : 8\n    카드매출금액 : 11947000\n    카드매출건수 : 417\n    점당매출금액 : 1493377\n    건당매출금액 : 28650\n'

In [22]:
city.head(2)

,기준년월,광역시도명,업종대분류,업종중분류,업종소분류,신규가맹점수,해지가맹점수,매출가맹점수,카드매출금액,카드매출건수,점당매출금액,건당매출금액
0,201902,강원,문화레져,동물,동물농장,0,0,8,11947000,417,1493377,28650
1,201902,강원,문화레져,동물,애완동물/용품,5,1,188,251553000,6788,1338046,37058

## 신한 - 서울시지역별 : 대출정보

In [24]:
seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준년월    109 non-null    int64
 1   법정동 이름  109 non-null    object
 2   법정동 코드  109 non-null    int64
 3   집계구 코드  109 non-null    object
 4   직장인여부   109 non-null    int64
 5   성별      109 non-null    int64
 6   연령구분    109 non-null    int64
 7   급여      109 non-null    float64
 8   가맹점매출   109 non-null    float64
 9   연금      109 non-null    float64
 10  총지출     109 non-null    float64
 11  총수신     109 non-null    float64
 12  예금, 적금  109 non-null    float64
 13  신탁      109 non-null    float64
 14  수익증권    109 non-null    float64
 15  신용대출    109 non-null    float64
 16  담보대출    109 non-null    float64
 17  주택대출    109 non-null    float64
 18  전세대출    109 non-null    float64
dtypes: float64(12), int64(5), object(2)
memory usage: 16.3+ KB

In [ ]:
''' 신한은행 - 서울시 지역 정보
    기준년월
    법정동 이름 : 가양동
    법정동 코드 : 1150010400
    집계구 코드 : 1150010400-101
    직장인여부 : 0
    성별 : 1
    연령구분 : 20
    급여 : 2,208,987
    가맹점매출 : 0.0
    연금 : 34,191
    총지출 : 2,273,590
    총수신 : 7,629,768
    예금,적금 : 3,545,905
    신탁 : 233,428
    수익증권 : 210,624
    신용대출 : 3,263,905
    담보대출 : 14,433,922
    주택대출 : 299,211
    전세대출 : 13,104,911
'''

In [25]:
seoul.head(2)

,기준년월,법정동 이름,법정동 코드,집계구 코드,직장인여부,성별,연령구분,급여,가맹점매출,연금,총지출,총수신,"예금, 적금",신탁,수익증권,신용대출,담보대출,주택대출,전세대출
0,201903,가양동,1150010400,1150010400-101,0,1,20,0.000000e+00,15040.026773,197.185239,7.173819e+05,2.928034e+06,1.616215e+06,134101.514616,131790.944139,2.101710e+05,1.247541e+06,148058.396527,8.391462e+05
1,201903,가양동,1150010400,1150010400-101,1,1,20,2.208987e+06,0.000000,34191.062305,2.273580e+06,7.629768e+06,3.545905e+06,233428.455452,210623.730218,3.263905e+06,1.443392e+07,298210.607477,1.310491e+07

In [26]:
seoul.describe()

,기준년월,법정동 코드,직장인여부,성별,연령구분,급여,가맹점매출,연금,총지출,총수신,"예금, 적금",신탁,수익증권,신용대출,담보대출,주택대출,전세대출
count,109.0,1.090000e+02,109.000000,109.000000,109.000000,1.090000e+02,109.000000,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02
mean,201903.0,1.144534e+09,0.495413,0.522936,39.816514,1.433423e+06,123276.133805,8.617902e+04,1.820371e+06,1.518168e+07,5.240574e+06,2.430674e+06,1.101080e+06,4.863506e+06,1.461642e+07,5.517103e+06,4.738611e+06
std,0.0,1.602900e+07,0.502288,0.501781,14.140934,1.535860e+06,151257.470081,2.716231e+05,1.083407e+06,1.271051e+07,3.591033e+06,3.383071e+06,1.361108e+06,5.603454e+06,1.103025e+07,4.879533e+06,5.172160e+06
min,201903.0,1.121510e+09,0.000000,0.000000,20.000000,0.000000e+00,0.000000,0.000000e+00,4.081740e+05,1.231982e+06,6.612143e+05,3.795724e+04,1.586278e+04,1.025223e+05,4.208611e+05,0.000000e+00,1.106918e+05
25%,201903.0,1.129013e+09,0.000000,0.000000,30.000000,0.000000e+00,15024.407921,6.048024e+03,9.435203e+05,5.833799e+06,2.754956e+06,2.656744e+05,1.832644e+05,9.593920e+05,6.494187e+06,1.438356e+06,7.388195e+05
50%,201903.0,1.150010e+09,0.000000,1.000000,40.000000,0.000000e+00,64041.890201,2.022405e+04,1.697988e+06,1.178928e+07,4.440306e+06,1.069309e+06,6.018787e+05,1.759193e+06,1.281266e+07,4.725182e+06,2.038903e+06
75%,201903.0,1.156013e+09,1.000000,1.000000,50.000000,2.921368e+06,170980.992851,7.675454e+04,2.625503e+06,2.030136e+07,7.057414e+06,3.628950e+06,1.528940e+06,9.107032e+06,2.207535e+07,8.393405e+06,7.875278e+06
max,201903.0,1.174010e+09,1.000000,1.000000,60.000000,4.482986e+06,728221.720000,2.674432e+06,7.343596e+06,5.921200e+07,1.607309e+07,2.190902e+07,6.149954e+06,2.547483e+07,5.674003e+07,2.019126e+07,2.172226e+07